spring:
  application:
    name: franchise
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://challenge.cpq8g28o4qad.us-east-2.rds.amazonaws.com:3306/franchise
    username: admin
    password: 2wsyNb6s3iI6QmxGCq65
